// Generated by assets/game/scripts/sync-browser-assets.mjs. Do not edit.
export const playerArtCatalog = {
  "human": {
    "version": "coach-oriented-v1",
    "rosterId": "human",
    "positions": {
      "lineman": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/lineman-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 8,
              "width": 44,
              "height": 54
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32,
              "y": 35
            }
          },
          "back": {
            "file": "master/lineman-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 7,
              "width": 44,
              "height": 55
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32,
              "y": 34.5
            }
          },
          "front45": {
            "file": "master/lineman-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 11,
              "y": 7,
              "width": 43,
              "height": 55
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 34.5
            }
          },
          "back45": {
            "file": "master/lineman-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 16,
              "y": 3,
              "width": 42,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 37,
              "y": 32.5
            }
          },
          "side": {
            "file": "master/lineman-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 19,
              "y": 4,
              "width": 25,
              "height": 57
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 32.5
            }
          },
          "prone": {
            "file": "master/lineman-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 4,
              "y": 22,
              "width": 54,
              "height": 40
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31,
              "y": 42
            }
          },
          "stunned": {
            "file": "master/lineman-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 6,
              "y": 23,
              "width": 55,
              "height": 39
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 33.5,
              "y": 42.5
            }
          }
        },
        "portrait": {
          "file": "master/lineman-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 4,
            "y": 20,
            "width": 152,
            "height": 119
          }
        }
      },
      "blitzer": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/blitzer-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 11,
              "y": 4,
              "width": 38,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30,
              "y": 33
            }
          },
          "back": {
            "file": "master/blitzer-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 4,
              "width": 37,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 33
            }
          },
          "front45": {
            "file": "master/blitzer-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 12,
              "y": 3,
              "width": 37,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 32.5
            }
          },
          "back45": {
            "file": "master/blitzer-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 15,
              "y": 3,
              "width": 38,
              "height": 60
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 34,
              "y": 33
            }
          },
          "side": {
            "file": "master/blitzer-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 17,
              "y": 4,
              "width": 29,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 33
            }
          },
          "prone": {
            "file": "master/blitzer-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 9,
              "y": 26,
              "width": 43,
              "height": 36
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 44
            }
          },
          "stunned": {
            "file": "master/blitzer-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 9,
              "y": 24,
              "width": 45,
              "height": 35
            },
            "footAnchor": {
              "x": 32,
              "y": 59
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 41.5
            }
          }
        },
        "portrait": {
          "file": "master/blitzer-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 19,
            "y": 4,
            "width": 122,
            "height": 152
          }
        }
      },
      "catcher": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/catcher-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 11,
              "y": 4,
              "width": 42,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 32,
              "y": 33.5
            }
          },
          "back": {
            "file": "master/catcher-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 12,
              "y": 4,
              "width": 42,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 33,
              "y": 33.5
            }
          },
          "front45": {
            "file": "master/catcher-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 11,
              "y": 4,
              "width": 43,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 33.5
            }
          },
          "back45": {
            "file": "master/catcher-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 4,
              "width": 43,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 34.5,
              "y": 33.5
            }
          },
          "side": {
            "file": "master/catcher-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 11,
              "y": 4,
              "width": 42,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 32,
              "y": 33.5
            }
          },
          "prone": {
            "file": "master/catcher-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 4,
              "y": 17,
              "width": 56,
              "height": 45
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32,
              "y": 39.5
            }
          },
          "stunned": {
            "file": "master/catcher-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 3,
              "y": 20,
              "width": 58,
              "height": 42
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32,
              "y": 41
            }
          }
        },
        "portrait": {
          "file": "master/catcher-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 11,
            "y": 12,
            "width": 137,
            "height": 144
          }
        }
      },
      "thrower": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/thrower-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 5,
              "y": 4,
              "width": 44,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 27,
              "y": 33
            }
          },
          "back": {
            "file": "master/thrower-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 3,
              "width": 50,
              "height": 60
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 35,
              "y": 33
            }
          },
          "front45": {
            "file": "master/thrower-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 5,
              "y": 5,
              "width": 50,
              "height": 57
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30,
              "y": 33.5
            }
          },
          "back45": {
            "file": "master/thrower-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 8,
              "y": 4,
              "width": 53,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 34.5,
              "y": 33
            }
          },
          "side": {
            "file": "master/thrower-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 12,
              "y": 4,
              "width": 35,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 29.5,
              "y": 33
            }
          },
          "prone": {
            "file": "master/thrower-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 3,
              "y": 18,
              "width": 58,
              "height": 40
            },
            "footAnchor": {
              "x": 32,
              "y": 58
            },
            "groundAnchor": {
              "x": 32,
              "y": 38
            }
          },
          "stunned": {
            "file": "master/thrower-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 5,
              "y": 22,
              "width": 55,
              "height": 40
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 42
            }
          }
        },
        "portrait": {
          "file": "master/thrower-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 4,
            "y": 15,
            "width": 152,
            "height": 130
          }
        }
      },
      "ogre": {
        "sizeClass": "big",
        "poses": {
          "front": {
            "file": "master/ogre-front.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 8,
              "y": 7,
              "width": 64,
              "height": 71
            },
            "footAnchor": {
              "x": 40,
              "y": 78
            },
            "groundAnchor": {
              "x": 40,
              "y": 42.5
            }
          },
          "back": {
            "file": "master/ogre-back.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 8,
              "y": 7,
              "width": 64,
              "height": 70
            },
            "footAnchor": {
              "x": 40,
              "y": 77
            },
            "groundAnchor": {
              "x": 40,
              "y": 42
            }
          },
          "front45": {
            "file": "master/ogre-front45.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 10,
              "y": 5,
              "width": 61,
              "height": 72
            },
            "footAnchor": {
              "x": 40,
              "y": 77
            },
            "groundAnchor": {
              "x": 40.5,
              "y": 41
            }
          },
          "back45": {
            "file": "master/ogre-back45.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 12,
              "y": 4,
              "width": 62,
              "height": 74
            },
            "footAnchor": {
              "x": 40,
              "y": 78
            },
            "groundAnchor": {
              "x": 43,
              "y": 41
            }
          },
          "side": {
            "file": "master/ogre-side.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 21,
              "y": 4,
              "width": 37,
              "height": 74
            },
            "footAnchor": {
              "x": 40,
              "y": 78
            },
            "groundAnchor": {
              "x": 39.5,
              "y": 41
            }
          },
          "prone": {
            "file": "master/ogre-prone.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 2,
              "y": 23,
              "width": 74,
              "height": 48
            },
            "footAnchor": {
              "x": 40,
              "y": 71
            },
            "groundAnchor": {
              "x": 39,
              "y": 47
            }
          },
          "stunned": {
            "file": "master/ogre-stunned.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 3,
              "y": 31,
              "width": 73,
              "height": 44
            },
            "footAnchor": {
              "x": 40,
              "y": 75
            },
            "groundAnchor": {
              "x": 39.5,
              "y": 53
            }
          }
        },
        "portrait": {
          "file": "master/ogre-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 4,
            "y": 15,
            "width": 152,
            "height": 130
          }
        }
      },
      "halfling": {
        "sizeClass": "small",
        "poses": {
          "front": {
            "file": "master/halfling-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 18,
              "y": 21,
              "width": 26,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31,
              "y": 41.5
            }
          },
          "back": {
            "file": "master/halfling-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 20,
              "y": 20,
              "width": 26,
              "height": 42
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 33,
              "y": 41
            }
          },
          "front45": {
            "file": "master/halfling-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 21,
              "y": 21,
              "width": 23,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 41.5
            }
          },
          "back45": {
            "file": "master/halfling-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 23,
              "y": 17,
              "width": 22,
              "height": 45
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 34,
              "y": 39.5
            }
          },
          "side": {
            "file": "master/halfling-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 22,
              "y": 19,
              "width": 18,
              "height": 42
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 31,
              "y": 40
            }
          },
          "prone": {
            "file": "master/halfling-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 27,
              "width": 39,
              "height": 29
            },
            "footAnchor": {
              "x": 32,
              "y": 56
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 41.5
            }
          },
          "stunned": {
            "file": "master/halfling-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 34,
              "width": 39,
              "height": 29
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 48.5
            }
          }
        },
        "portrait": {
          "file": "master/halfling-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 4,
            "y": 5,
            "width": 152,
            "height": 149
          }
        }
      }
    }
  },
  "orc": {
    "version": "coach-oriented-v1",
    "rosterId": "orc",
    "positions": {
      "orc-lineman": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/orc-lineman-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 4,
              "y": 3,
              "width": 49,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 28.5,
              "y": 32
            }
          },
          "back": {
            "file": "master/orc-lineman-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 3,
              "width": 49,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 34.5,
              "y": 32
            }
          },
          "front45": {
            "file": "master/orc-lineman-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 8,
              "y": 3,
              "width": 45,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 32.5
            }
          },
          "back45": {
            "file": "master/orc-lineman-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 17,
              "y": 3,
              "width": 43,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 38.5,
              "y": 32.5
            }
          },
          "side": {
            "file": "master/orc-lineman-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 9,
              "y": 4,
              "width": 30,
              "height": 57
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 24,
              "y": 32.5
            }
          },
          "prone": {
            "file": "master/orc-lineman-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 2,
              "y": 23,
              "width": 57,
              "height": 39
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 42.5
            }
          },
          "stunned": {
            "file": "master/orc-lineman-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 4,
              "y": 21,
              "width": 57,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32.5,
              "y": 41.5
            }
          }
        },
        "portrait": {
          "file": "master/orc-lineman-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 4,
            "y": 15,
            "width": 152,
            "height": 129
          }
        }
      },
      "orc-blitzer": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/orc-blitzer-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 9,
              "width": 41,
              "height": 52
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 35
            }
          },
          "back": {
            "file": "master/orc-blitzer-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 5,
              "width": 44,
              "height": 56
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 32,
              "y": 33
            }
          },
          "front45": {
            "file": "master/orc-blitzer-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 15,
              "y": 7,
              "width": 39,
              "height": 56
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 34.5,
              "y": 35
            }
          },
          "back45": {
            "file": "master/orc-blitzer-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 5,
              "width": 41,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 33.5,
              "y": 34
            }
          },
          "side": {
            "file": "master/orc-blitzer-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 18,
              "y": 4,
              "width": 27,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 33
            }
          },
          "prone": {
            "file": "master/orc-blitzer-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 9,
              "y": 16,
              "width": 44,
              "height": 38
            },
            "footAnchor": {
              "x": 32,
              "y": 54
            },
            "groundAnchor": {
              "x": 31,
              "y": 35
            }
          },
          "stunned": {
            "file": "master/orc-blitzer-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 12,
              "y": 20,
              "width": 42,
              "height": 35
            },
            "footAnchor": {
              "x": 32,
              "y": 55
            },
            "groundAnchor": {
              "x": 33,
              "y": 37.5
            }
          }
        },
        "portrait": {
          "file": "master/orc-blitzer-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 14,
            "y": 4,
            "width": 131,
            "height": 152
          }
        }
      },
      "big-un-blocker": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/big-un-blocker-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 5,
              "y": 4,
              "width": 49,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 29.5,
              "y": 33
            }
          },
          "back": {
            "file": "master/big-un-blocker-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 8,
              "y": 4,
              "width": 47,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 33
            }
          },
          "front45": {
            "file": "master/big-un-blocker-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 8,
              "y": 4,
              "width": 45,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 33.5
            }
          },
          "back45": {
            "file": "master/big-un-blocker-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 14,
              "y": 4,
              "width": 43,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 35.5,
              "y": 33
            }
          },
          "side": {
            "file": "master/big-un-blocker-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 17,
              "y": 4,
              "width": 26,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30,
              "y": 33
            }
          },
          "prone": {
            "file": "master/big-un-blocker-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 4,
              "y": 21,
              "width": 54,
              "height": 40
            },
            "footAnchor": {
              "x": 32,
              "y": 61
            },
            "groundAnchor": {
              "x": 31,
              "y": 41
            }
          },
          "stunned": {
            "file": "master/big-un-blocker-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 3,
              "y": 20,
              "width": 58,
              "height": 40
            },
            "footAnchor": {
              "x": 32,
              "y": 60
            },
            "groundAnchor": {
              "x": 32,
              "y": 40
            }
          }
        },
        "portrait": {
          "file": "master/big-un-blocker-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 8,
            "y": 4,
            "width": 144,
            "height": 152
          }
        }
      },
      "orc-thrower": {
        "sizeClass": "standard",
        "poses": {
          "front": {
            "file": "master/orc-thrower-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 8,
              "y": 4,
              "width": 38,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 27,
              "y": 33.5
            }
          },
          "back": {
            "file": "master/orc-thrower-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 6,
              "y": 3,
              "width": 42,
              "height": 60
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 27,
              "y": 33
            }
          },
          "front45": {
            "file": "master/orc-thrower-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 6,
              "y": 5,
              "width": 43,
              "height": 58
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 27.5,
              "y": 34
            }
          },
          "back45": {
            "file": "master/orc-thrower-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 3,
              "width": 40,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 33,
              "y": 32.5
            }
          },
          "side": {
            "file": "master/orc-thrower-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 13,
              "y": 3,
              "width": 32,
              "height": 59
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 29,
              "y": 32.5
            }
          },
          "prone": {
            "file": "master/orc-thrower-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 3,
              "y": 21,
              "width": 55,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 30.5,
              "y": 41.5
            }
          },
          "stunned": {
            "file": "master/orc-thrower-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 3,
              "y": 22,
              "width": 57,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 42.5
            }
          }
        },
        "portrait": {
          "file": "master/orc-thrower-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 15,
            "y": 4,
            "width": 129,
            "height": 152
          }
        }
      },
      "troll": {
        "sizeClass": "big",
        "poses": {
          "front": {
            "file": "master/troll-front.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 11,
              "y": 4,
              "width": 57,
              "height": 74
            },
            "footAnchor": {
              "x": 40,
              "y": 78
            },
            "groundAnchor": {
              "x": 39.5,
              "y": 41
            }
          },
          "back": {
            "file": "master/troll-back.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 13,
              "y": 4,
              "width": 55,
              "height": 70
            },
            "footAnchor": {
              "x": 40,
              "y": 74
            },
            "groundAnchor": {
              "x": 40.5,
              "y": 39
            }
          },
          "front45": {
            "file": "master/troll-front45.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 15,
              "y": 6,
              "width": 49,
              "height": 68
            },
            "footAnchor": {
              "x": 40,
              "y": 74
            },
            "groundAnchor": {
              "x": 39.5,
              "y": 40
            }
          },
          "back45": {
            "file": "master/troll-back45.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 14,
              "y": 5,
              "width": 52,
              "height": 72
            },
            "footAnchor": {
              "x": 40,
              "y": 77
            },
            "groundAnchor": {
              "x": 40,
              "y": 41
            }
          },
          "side": {
            "file": "master/troll-side.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 20,
              "y": 4,
              "width": 40,
              "height": 75
            },
            "footAnchor": {
              "x": 40,
              "y": 79
            },
            "groundAnchor": {
              "x": 40,
              "y": 41.5
            }
          },
          "prone": {
            "file": "master/troll-prone.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 11,
              "y": 24,
              "width": 57,
              "height": 46
            },
            "footAnchor": {
              "x": 40,
              "y": 70
            },
            "groundAnchor": {
              "x": 39.5,
              "y": 47
            }
          },
          "stunned": {
            "file": "master/troll-stunned.png",
            "width": 80,
            "height": 80,
            "bounds": {
              "x": 11,
              "y": 25,
              "width": 55,
              "height": 44
            },
            "footAnchor": {
              "x": 40,
              "y": 69
            },
            "groundAnchor": {
              "x": 38.5,
              "y": 47
            }
          }
        },
        "portrait": {
          "file": "master/troll-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 10,
            "y": 4,
            "width": 140,
            "height": 152
          }
        }
      },
      "goblin-lineman": {
        "sizeClass": "small",
        "poses": {
          "front": {
            "file": "master/goblin-lineman-front.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 16,
              "y": 22,
              "width": 34,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 33,
              "y": 42.5
            }
          },
          "back": {
            "file": "master/goblin-lineman-back.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 15,
              "y": 21,
              "width": 32,
              "height": 41
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31,
              "y": 41.5
            }
          },
          "front45": {
            "file": "master/goblin-lineman-front45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 17,
              "y": 21,
              "width": 33,
              "height": 42
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 33.5,
              "y": 42
            }
          },
          "back45": {
            "file": "master/goblin-lineman-back45.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 19,
              "y": 18,
              "width": 31,
              "height": 45
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 34.5,
              "y": 40.5
            }
          },
          "side": {
            "file": "master/goblin-lineman-side.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 17,
              "y": 18,
              "width": 30,
              "height": 44
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 32,
              "y": 40
            }
          },
          "prone": {
            "file": "master/goblin-lineman-prone.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 9,
              "y": 33,
              "width": 44,
              "height": 29
            },
            "footAnchor": {
              "x": 32,
              "y": 62
            },
            "groundAnchor": {
              "x": 31,
              "y": 47.5
            }
          },
          "stunned": {
            "file": "master/goblin-lineman-stunned.png",
            "width": 64,
            "height": 64,
            "bounds": {
              "x": 10,
              "y": 32,
              "width": 43,
              "height": 31
            },
            "footAnchor": {
              "x": 32,
              "y": 63
            },
            "groundAnchor": {
              "x": 31.5,
              "y": 47.5
            }
          }
        },
        "portrait": {
          "file": "master/goblin-lineman-portrait.png",
          "width": 160,
          "height": 160,
          "bounds": {
            "x": 4,
            "y": 10,
            "width": 152,
            "height": 139
          }
        }
      }
    }
  }
} as const;
